---

- name: jdk folder creation
  file:
    path: /opt/jdk
    state: directory
- name: user creation
  user:
    name: "{{ owner }}"
    comment: "{{ owner }}"
    home: /opt/{{ owner }}
- name: OpenJdk 11 installation from source
  unarchive:
    src: https://s3-ap-southeast-1.amazonaws.com/java-tomcat-directory/OpenJDK11U-jdk_x64_linux_hotspot_11.0.2_7.tar.gz
    dest: /opt/jdk
    extra_opts: [--strip-components=1]
    remote_src: yes
- name: copy jdk11 environment file to profile
  copy:
    src: jdk11.sh
    dest: /etc/profile.d/
- name: source jdk11 environment file
  shell: source /etc/profile.d/jdk11.sh
- name: java alternatives path installation
  command: alternatives --install /usr/bin/java java /opt/jdk/bin/java 2
- name: Extract tomcat9 zip file
  unarchive:
    src: https://s3-ap-southeast-1.amazonaws.com/java-tomcat-directory/apache-tomcat-9.0.14.tar.gz
    dest: /opt/{{ owner }}
    extra_opts: [--strip-components=1]
    owner: "{{ owner }}"
    group: "{{ group }}"
    remote_src: yes
- name: Remove default files and folder from tomcat
  file:
    path: /opt/{{ owner }}/webapps/{{ item }}
    state: absent
  with_items:
  - ROOT/asf-logo-wide.svg
  - ROOT/bg-button.png
  - ROOT/bg-middle.png
  - ROOT/bg-nav.png
  - ROOT/bg-upper.png
  - ROOT/favicon.ico
  - ROOT/index.jsp
  - ROOT/RELEASE-NOTES.txt
  - ROOT/tomcat.css
  - ROOT/tomcat.gif
  - ROOT/tomcat.png
  - ROOT/tomcat-power.gif
  - ROOT/tomcat.svg
  - ROOT/WEB-INF
  - docs
  - examples
  - host-manager
  - manager
- name: copy tomcat system service
  template:
    src: tomcat.service.j2
    dest: /usr/lib/systemd/system/tomcat9.service
- name: tomcat service enable
  systemd:
    name: tomcat9
    enabled: yes
    masked: no
- name: Monitoring Script Folder
  file:
    path: /opt/{{ owner }}/webapps/monitor/
    recurse: yes
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
- name: Monitoring Script file Copy
  copy:
    src: aws_monitor.html
    dest: /opt/{{ owner }}/webapps/monitor/
    owner: "{{ owner }}"
    group: "{{ group }}"
- name: artifact deployment
  copy:
    src: "{{ module_name }}.war"
    dest: /opt/{{ owner }}/webapps/{{ module_name }}.war
    owner: "{{ owner }}"
    group: "{{ group }}"
  notify: Restart Tomcat
- name: Force a restart if configuration has changed
  meta: flush_handlers
- name: sleep timeout
  shell: sleep 10s
